apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.volumes.nginxConfig.name }}
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        location /static/ {
            root /usr/share/nginx/html;
        }

        location /api/ {
            proxy_pass http://localhost:5000;
        }

        location /submit {
            proxy_pass http://localhost:5000;
        }
    }
